### ISSUE TITLE
Aosip compilation problem.

### ISSUE THREAD

**Issue by Apon77** [dracarys18/NotKernel_Mido#6]
After the implementation of wireguard, facing some problem to compile aosip rom. First flock not allowed message came, then after fixing it, curl not allowed message came, then after fixing this. Host can no solved message came. The log of the last errors is https://hastebin.com/uvurakerol.makefile

**Comment by dracarys18** [comment]
Revert this commit
https://github.com/dracarys18/NotKernel_Mido/commit/d15416938a70a08e598b825beff612b5cf197abd
or remove that script and clone Wireguard locally. If you still have any problems ping me in t.me/notkernel telegram
